version: 2

models:
  - name: stations
    columns:
      - name: station_id
        data_tests:
          - not_null
          - unique

  - name: prices
    columns:
      - name: station_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stations')
                field: station_id
      - name: fetched_at
        data_tests:
          - not_null

  - name: price_changes
    columns:
      - name: station_id
        data_tests:
          - not_null
      - name: changed_at
        data_tests:
          - not_null
